# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc0b2b9bfe0d4639fcf0a35c16611707003ab2861311a54eabbbacfdfc755fb4ad81a3876270c073ed4aa3c4af202289bef13caee2e7bb6ae3b124067689e6e9
  twilio_account_sid: ACd32daebfbd0ff5e76a386bc82fb290a0
  twilio_auth_token: f163dd798c9c42ae4e12a2cde9ce0973

test:
  secret_key_base: de63a5b7a99e0bf58b117015cc2ff8f4e0d154aac8627c0a1bab41190c455ad4c2be4844b525378089202988c1bcdfc585c282389f25caac60ccb3c5aa4bf651
  twilio_account_sid: ACd32daebfbd0ff5e76a386bc82fb290a0
  twilio_auth_token: f163dd798c9c42ae4e12a2cde9ce0973

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_account_sid: ACd32daebfbd0ff5e76a386bc82fb290a0
  twilio_auth_token: f163dd798c9c42ae4e12a2cde9ce0973
